#pragma once

// heresy...
#include <cstdint>
#include <filesystem>
#include <unordered_map>
#include <vector>
#include <string>
#include <fstream>

// autogenerated
enum entry_set
{
    entry_set_start,
    defcolor_bar,
    defcolor_base,
    defcolor_pop1,
    defcolor_pop2,
    defcolor_back,
    defcolor_margin,
    defcolor_margin_hover,
    defcolor_margin_active,
    defcolor_list_item,
    defcolor_list_item_hover,
    defcolor_list_item_active,
    defcolor_cursor,
    defcolor_at_cursor,
    defcolor_highlight_cursor_line,
    defcolor_highlight,
    defcolor_at_highlight,
    defcolor_mark,
    defcolor_text_default,
    defcolor_comment,
    defcolor_comment_pop,
    defcolor_keyword,
    defcolor_str_constant,
    defcolor_char_constant,
    defcolor_int_constant,
    defcolor_float_constant,
    defcolor_bool_constant,
    defcolor_preproc,
    defcolor_include,
    defcolor_special_character,
    defcolor_ghost_character,
    defcolor_highlight_junk,
    defcolor_highlight_white,
    defcolor_paste,
    defcolor_undo,
    defcolor_back_cycle,
    defcolor_text_cycle,
    defcolor_line_numbers_back,
    defcolor_line_numbers_text,
    fleury_color_cursor_inactive,
    fleury_color_index_product_type,
    fleury_color_index_sum_type,
    fleury_color_index_function,
    fleury_color_index_constant,
    fleury_color_index_macro,
    fleury_color_index_4coder_command,
    fleury_color_index_comment_tag,
    fleury_color_index_decl,
    fleury_color_comment_user_name,
    fleury_color_error_annotation,
    fleury_color_warning_annotation,
    fleury_color_syntax_crap,
    fleury_color_operators,
    fleury_color_inactive_pane_overlay,
    fleury_color_inactive_pane_background,
    fleury_color_file_progress_bar,
    fleury_color_brace_highlight,
    fleury_color_brace_line,
    fleury_color_brace_annotation,
    // NOTE(para): not supported, can't test
    //fleury_color_cursor_macro,
    //fleury_color_cursor_power_mode,
    //fleury_color_plot_cycle,
    fleury_color_token_highlight,
    fleury_color_token_minor_highlight,
    entry_set_end
};